### PR TITLE
Add preliminary version of snapshot diff

### PR DESCRIPTION
**Pull request by dogboydog**
Use Diff2HTML package to generate HTML diff from jest failure message

Right now it goes into the span below the test result

### CODE REVIEW

**Comment by dogboydog** [comment]
Made the failing test that demonstrates the snapshot diff pass for the CI check. Maybe we could set the npm scripts up in such a way so that just "jest" doesn't run failing tests but some other scripts would include failing tests to easily demonstrate the project

**Comment by dkelosky** [comment]
I started making some integration tests to do this.  I captured the raw data here: https://github.com/dkelosky/jest-stare/tree/master/__tests__/data

Do you think that would work?

**Comment by dogboydog** [comment]
I haven't seen how the JSON  works. Are those full results for a test which you then use to generate a report? I think that works, then we could set up tasks to use those JSON files. Maybe that's clearer than having special tests that only run when we want them to

**Comment by dkelosky** [comment]
Before we publish, how do you get actual values for the first red arrow item?  

Also, what do you think of the "raw" button to expand the raw failure text?  Should it be expanded by default if the failure is a non-snapshot?


diff start

**Comment by dogboydog** [comment]
Whoa you got the table to work! It doesn't look like that for me.  Maybe different browsers display it differently?

Not 100% Sure what the numbers mean.  I guess they are additions and deletions but not sure about the 6 and 17. I just stuck that in there because if I didn't have it Diff2HTML gave me back blank HTML.  Besides the 6 and 17, I guess we could count lines starting with + or -  to get a rough guess?

I think if the failure is a non-snapshot we can probably just put the text below it. It would be kind of cool to be able to expand the raw failure text even for snapshots

I didn't know if we should publish yet since the diff didn't look good for me and I thought you might want to mess with it and stick it somewhere else. I could change the branch from master to another if you want. Up to you

**Comment by dogboydog** [comment]
Merged into a development branch instead of master. Thanks!

**Pull request closed without merging**
