### PR TITLE
Add support for image-snapshots

### LINKED ISSUE #56: Support visual regression snapshot using jest-image-snapshot
It would be great to check visual regression just like snapshot diff :D

- https://github.com/americanexpress/jest-image-snapshot

### PR DESCRIPTION
**Pull request by mnikkane**
Add support to show jest image snapshots (https://github.com/americanexpress/jest-image-snapshot)  fail diff images in Jest Stare HTML.

Added some tests and example to demo feature (`npm run example`). 

Resolves #56

### CODE REVIEW

**Comment by dkelosky** [comment]
Looks great - thanks for making the changes!  CI seems hung, so I'll merge and see if I can get a test to pass before publishing

**Comment by dkelosky** [comment]
hi @mnikkane , I tried using `jest --testRegex __tests__.*\\DemoTests.example.ts` and get:  
image

Do I need to do something else?  All other tests pass.

**Comment by mnikkane** [comment]
@dkelosky Should not need anything more. I tested this with clean clone from the repo and works on OSX and Linux. Should look like this: 

image

Do you have the diff image copied to `results/jest-stare/image_snapshot_diff` folder (should be copied there automatically when tests are executed and diff image detected from jest failure)? Could you please inspect the image tag in the HTML, is it pointing correctly to that file?

**Comment by dkelosky** [comment]
That looks really cool!  

I should have known better to check the things you mentioned!  The diff is here (not in `results/jest-stare/image_snapshot_diff`):
image


The inspect is here:
image


Commuting to work now, so I take a look again a little bit later and see what's going on for my Window's tests!  

Side question, if you use the `jest-stare` package on a project without `jest-image-snapshot`, do you have any problems?

**Comment by dkelosky** [comment]
BTW - this is working on Linux.

**Comment by mnikkane** [comment]
It must be that the file copying does not work correctly on Windows. Most likely there is wrong slash used, thinking around line 116: https://github.com/dkelosky/jest-stare/pull/62/files#diff-a0d21bdd46ec63299f7fff7ace802e9cR116  

Or maybe this should be defined in platform independent way: https://github.com/dkelosky/jest-stare/pull/62/files#diff-9d39289bc0263729591ddce77a411490R107

Seems to work w/o problems on project with no dependency to jest-image-snapshot. The changes in this PR has no direct dependency to jest-image-snapshot, they are only reading the jest failure message, which the jest-image-snapshot will generate.

**Comment by dkelosky** [comment]
thanks for the info.

This line is setting `diffImagePath` to null: https://github.com/dkelosky/jest-stare/pull/62/files#diff-a0d21bdd46ec63299f7fff7ace802e9cR108

**Comment by mnikkane** [comment]
I can take a look of this on Sunday/Monday, msot likely the regexp needs to understand windows path separator (`\`). Or did you resolve the problem already, as I saw you made the release?

**Comment by dkelosky** [comment]
Yep, got it sorted, I commented I'm #56 instead of here (I don't know why).  I just needed a new regex and to handle a bizarre ansi color character that surfaced with the new regex :smile:. 

Thanks for taking the time!

**Comment by mnikkane** [comment]
Ok, all good then. Thanks for a good work, love open source 🙂

**Pull request merged**
